### ISSUE TITLE
"Date or number format" does not work when "Include header" is enabled

### ISSUE THREAD

**Issue by DiegoQueiroz** [jlolling/talendcomp_tFileExcel#11]
When you set a "Date or number format" for a column when the "Include header" is enabled, the formatting does not apply to data cells.

**Comment by jlolling** [comment]
Actually this was the bug which I have solved in the last release. Are you sure you are using the last release 10.2?

**Comment by DiegoQueiroz** [comment]
I wasn't in the last version, indeed. I was using 10.0. I just updated and the problem doesn't happens in the last version.

Thank you for pointing this. ;)
