### ISSUE TITLE
Providing the sheet index results in compile error

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tFileExcel#13]
As documented I provide the index of the sheet in the properties.
I know in former versions this worked, but now I get an compile error:
**The method setTargetSheetName(String) in the type SpreadsheetFile is not applicable for the arguments (int)**	

Codeline is:
`tFileExcelSheetOutput_1.setTargetSheetName(0);`

**Comment by jlolling** [comment]
The idea was to have an name for the sheet because of the ability to create this sheet.
If an index is provided as sheet address the sheet must exists already.

**Comment by mattywausb** [comment]
The idea is ok, but then the documentation should reflect it

**Comment by jlolling** [comment]
In the new release 10.3 this issue is solved.
