### ISSUE TITLE
Option to delete template row

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tFileExcel#14]
"Schiebe aktuelle Zeile vor dem Schreiben" is very useful to provide exel reports with a summary row  by using a template like this:
- header row
- template data row
- Summary row

All provided rows are inserted nicely. To make it perfect, it would be nice to remove the shifted template row afterwards, because it always stays unter the inserted data. Two solutions: 

* have an option to delete the shifted row after data insertion
* have a dedicated component to delete rows (which might be useful in other scenarios too)

[demo_template_file.xlsx](https://github.com/jlolling/talendcomp_tFileExcel/files/2329284/demo_template_file.xlsx)
[demo_report_file.xlsx](https://github.com/jlolling/talendcomp_tFileExcel/files/2329289/demo_report_file.xlsx)

Actual Workaround is: Hide the template row. 

Best regards
mwab

**Comment by jlolling** [comment]
If the shifted row is actually a template, why shifting the row?
One way to remove rows is the option "Remove last empty rows". This option removes all rows after the last written row. Currently the label of this option is wrong.

**Comment by mattywausb** [comment]
Please look at my examples. There are two template rows, one for the detail data and one summary row below. The summare must move down until all data is inserted. Afterwards a second data flow will provide the summary data. When I "remove last empty rows" after inserting the detail data, the summary row is gone.

**Comment by jlolling** [comment]
Yes sorry, you are right. Your first suggestion is on my opinion the best solution and perhaps also the quick win solution. I will implement this in the next days.
Best regards
Jan

**Comment by jlolling** [comment]
Sorry for delay, I had some urgent issues. I will implement this in the next release.
Best regards
Jan

**Comment by jlolling** [comment]
I will create a component to delete rows. This looks like the most useful way.

**Comment by jlolling** [comment]
will not done
