### ISSUE TITLE
tFileExcelSheetOutput Formatangaben in falscher Spalte

### ISSUE THREAD

**Issue by cK4i** [jlolling/talendcomp_tFileExcel#16]
Hi J,
wenn in der tFileExcelSheetOutput Komponente eine andere Startspalte als A angegeben wird stimmt die Zuordnung des "Datums- oder Zahlenformat"s in der Spaltenkonfiguration nicht mehr.

Wenn zum Beispiel das Schema Spalte1 und Spalte2 enthällt, für Spalte2 ein Format angegeben wird und die Startspalte auf B steht wird das Format auf Spalte1 angewandt.

Viele Grüße,
K

**Comment by jlolling** [comment]
Ich kann den Fehler nun nachvollziehen. Sorry, ich kümmere mich darum.

**Comment by jlolling** [comment]
Der Fehler ist in Version 11.0 gefixt.
