### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by jkeruzec** [jlolling/talendcomp_tFileExcel#18]
Could someone point me how to install those components ? 

Are they compatible with version 7.1.x of Talend ? 

Thanks,

**Comment by jkeruzec** [comment]
Ok found something usefull here : 
https://help.talend.com/reader/2AWmA~w4VvlfP3JC7dTR2w/khP8_MmkQlSLK5OkrZc7eg

I try it with version 7.1

**Comment by dogleg69** [comment]
Yes, I am using them with 7.1.1.  You have the correct link on how to install them.  Just make sure to note the instructions at the bottom of that link.  Cntrl+Shift+F3 or restart is what I have found is best after installation.

**Comment by jlolling** [comment]
These components are compatible with 7.1.1 and the way to install them ist the same as in the former versions.
