### ISSUE TITLE
Using of tFileExcelSheetOutput Custom Component

### ISSUE THREAD

**Issue by chaitanyasrigakollu** [jlolling/talendcomp_tFileExcel#2]
Hi Jlolling,

I have excel sheet with multiple formulae. The entire excel is depend upon on the one cell value.
For example I have value X in A1 cell and Cell B1, B2, B3 etc are relied on the A1 cell.

And I'm trying to populate the A1 cell dynamically using the tfileexcelsheetoutput component. My concern is I'm able to populate the A1 cell dynamically, but the excel sheet is not get refreshed while I'm opening the file. All the B1, B2, B3 values are remain the same even the A1 cell is updated.

Could anyone please help me, how should the sheet should be refreshed while I'm opening the file every time.

Really, solution to this issue will be a great help for me. I have multiple jobs where I need to update the template with the desired values in one sheet and other sheets will be populated based on the main sheet values.

Thanks in advance!

Thanks,
Chaitanya

**Comment by jlolling** [comment]
Did you have activated the option Recalculate in the tFileExcelWorkbookSave component?

**Comment by jlolling** [comment]
I would be great to have a test job to see what you mean. The work with formulas is actually pretty easy and works without any problems in a lot of my projects.

**Comment by jlolling** [comment]
In my test cases and projects, the calculation of formula values works well. Until I do not have a bit more information. I cannot reproduce it.

**Comment by chaitanyasrigakollu** [comment]
Hi jlolling,

Now It's even working good for me as well.

Thank you very much for your response.

I have few templates with cells protected and we don't want to fill values
on  those cells with the new values.  but tfikeexcel components have the
capability in writing in those protected cells as well. Is there an any
option to stop the job with the error notification trying to write on
protected cells which can't be possible.

Could you please suggest.

Thanks in advance!

I would really thanks and appreciate for your efforts in designing excel
components with the additional features. That's really fulfilling few of my
job requirements. Thanks again!!!

Regards,
Chaitanya

**Comment by jlolling** [comment]
Yes it is possible. All cells carries this information and I can check that information.
I will take that as new feature requirement and add an option to permit writing into protected cells.
Best regards
Jan

**Comment by chaitanyasrigakollu** [comment]
Thanks for the response!!

Is there a chance to have these custom components as Talend inbuilt
components in the next version of Talend.

Thanks,
Chaitanya

**Comment by jlolling** [comment]
Hi @chaitanyasrigakollu  I do not think so. Talend includes components from the community only if there is a marketing advantage or there is no alternative to a mandatory functionality.
Do no care what Talend does, their components often not really maintained with "love".
