### ISSUE TITLE
The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx Workbook

### ISSUE THREAD

**Issue by jkeruzec** [jlolling/talendcomp_tFileExcel#20]
I have a large Excel files to generate but I have this issues : 

I use latest version of tFileExcel + Talend V7.2.1.20190620_1446

```
Exception in component tFileExcelSheetOutput_3 (export_all_parts_list)
java.lang.IllegalStateException: The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx Workbook
	at org.apache.poi.xssf.model.StylesTable.createCellStyle(StylesTable.java:831)
	at org.apache.poi.xssf.usermodel.XSSFWorkbook.createCellStyle(XSSFWorkbook.java:746)
	at org.apache.poi.xssf.streaming.SXSSFWorkbook.createCellStyle(SXSSFWorkbook.java:874)
	at de.jlo.talendcomp.excel.SpreadsheetOutput.setupStyle(SpreadsheetOutput.java:898)
	at de.jlo.talendcomp.excel.SpreadsheetOutput.writeCellValue(SpreadsheetOutput.java:505)
	at de.jlo.talendcomp.excel.SpreadsheetOutput.writeRow(SpreadsheetOutput.java:229)
```
Checkbox Use existent style is not ticked.

Can you help ?

Thanks.

**Comment by jlolling** [comment]
I will check that. This should not happen.

**Comment by jlolling** [comment]
Can you show me your job design as screenshot?

**Comment by jkeruzec** [comment]
Yes for sure. As a workaround I did it in two times and assemble lines in the end (9MB file, ~28000 lines, column A to BW ) I use a template also.

![image](https://user-images.githubusercontent.com/3499632/68288228-516cf680-0084-11ea-8621-19d8ec731d77.png)
[template.xlsx](https://github.com/jlolling/talendcomp_tFileExcel/files/3813777/template.xlsx)

**Comment by jlolling** [comment]
Ok, in the template you have styles I guess.
Excel has indeed a maximum number of styles but do not provide a way to organize them.
I have to compare the styles and take care I avoid as much as possible creating the same style for every line.

**Comment by jlolling** [comment]
I have checked the code dealing with styles and this code already reuse existing styles in the way, the component read the necessary styles from the first/second data target row and reuse them.
Means if you restarts this process often the number of styles increases.
Could you tell how often you call the last part (triggered by the last Iterate flow) containing the tFileExcelSheetOutput?

**Comment by jkeruzec** [comment]
Screenshot with information from the run : 

![image](https://user-images.githubusercontent.com/3499632/68380008-4d59db00-014f-11ea-8dca-4f479b48a73a.png)

**Comment by jlolling** [comment]
I just have some changes made to improve this situation and test that currently.
At the moment I suggest you do not write into to the excel sheet within you job, instead you write into a tHashOutput collecting there all rows you want to write into your sheet and after that use a tHashInput and write the whole sheet at once. This way you will prevent the styles problem.
