### ISSUE TITLE
Insert a chart (png or so) into an Excel sheet

### ISSUE THREAD

**Issue by HTPC-Schrauber** [jlolling/talendcomp_tFileExcel#21]
Is this possible?

**Comment by jlolling** [comment]
Unfortunately not. You can have charts in a file read as template but the current API does not allow stable to create charts.
I will keep an eye on the API, perhaps sometimes it is possible.
When I need a chart, I create a chart based on a so called Table and update in the Talend Job this table (write into a area of this table and the table will automatically updated in its structure). This leads into an updated chart or pivot table.

**Comment by jlolling** [comment]
I will check if the API allows to insert static images, but it is actually better to add them into a template and read the template and fill your data into it.
