### ISSUE TITLE
Append Rows Using Existing Styles

### ISSUE THREAD

**Issue by douglim** [jlolling/talendcomp_tFileExcel#23]
I’m trying to append rows into a template and have the cells in the appended rows copy the existing styles from the first row appended.

•	The background color for cells is getting overwritten and not copied into new rows
•	The original number formatting on the first row appended is retained, but not carried forward into subsequent appended rows

I have attached a test case including:

- Zip export of a minimal Talend job demonstrating the issue - uses only standard Talend components, no external data sources, and uses tFileExcelWorkbookOpen, tFileExcelSheetOutput, tFileExcelReferencedCellOutput, and tFileExcelWorkbookSave
- WTandASPPrices_template.xlsx - template Excel workbook
- WTandASPPrices_2020-05-04_test.xlsx - result of test
- WTandASPPrices_2020-05-04_expected.xlsx - expected results

My development environment is Talend Studio 7.1.1 on Windows
Installed version of tFileExcel components - v 12.1 20200329 build

[tFileExcel_Component_Test.zip](https://github.com/jlolling/talendcomp_tFileExcel/files/4576019/tFileExcel_Component_Test.zip)

**Comment by jlolling** [comment]
Everything works fine. You have just missed to set the necessary options in tFileExcelSheetOutput component.
The options: 
* Reuse existing style
must be set at least to get the styles copied.

**Comment by jlolling** [comment]
Here the screenshot of the change to get your use case running.
![tFileExcelSheetOutput_necessary_changes](https://user-images.githubusercontent.com/8038781/81058582-fef38200-8ece-11ea-839e-c4719bfb8a12.png)

**Comment by jlolling** [comment]
I suggest you check that again and close this issue if you are satisfied with my answer.

**Comment by douglim** [comment]
Confirmed - works as expected. User error. Sorry. Thanks for the help.
