### ISSUE TITLE
 prevent writing cell style in SheetOutput like it's available in tFileExcelReferencedCellOutput?

### ISSUE THREAD

**Issue by manueldion** [jlolling/talendcomp_tFileExcel#26]
Hi Jan,
-- Using Talend 7.3.1 using V 12.1 and V12.4 versions
-- Add no issue in Talend 6.2.1 using ( V 10.2 but not 100% sure of the version)

First, I have been using this since, well,  forever (Talend 5.2 was my 1st version)
I could not live without your Excel Components...

Now to the question...
I have the same issue found in https://github.com/jlolling/talendcomp_tFileExcel/issues/17
but it occurs when I use tFileExcelSheetOutput. For Text cell it seems that there is no way to prevent writing cell style

The template is fine for Column A, C and D but with text cell like in the B column one we loose the template style.

Any suggestion to handle this would be cool!

![image](https://user-images.githubusercontent.com/73551643/97341476-7d682580-185b-11eb-8e6f-1e16007382be.png)
![image](https://user-images.githubusercontent.com/73551643/97341213-24988d00-185b-11eb-8d69-78a2e0e721a6.png)

Thanks,
Manuel

**Comment by jlolling** [comment]
Do you mean writing in existing cells and in case of text typed cells the existing style will be damaged?

**Comment by jlolling** [comment]
I will check that, sorry for the delay.

**Comment by manueldion** [comment]
Hey. no problem with the delay.
I meant that the output for text column override the destination cell format
I think we miss an option that act like the doNotSetCellStyle of tFileExcelReferencedCellOutput

**Comment by jlolling** [comment]
The reason for the style damage was the function to take care a text is recognized as text in Excel. Therefore some users expected to set explicitly the cell type to text. I will add an option to switch off this behavior.

**Comment by jlolling** [comment]
I have solved the issue in the upcoming version 12.5. I am currently testing a bit and will publish it in the next few days.
![tFileExcelSheetOutput_prevent_changing_cell_style](https://user-images.githubusercontent.com/8038781/103585545-87557700-4ee3-11eb-8a56-e78617e76eff.png)

**Comment by jlolling** [comment]
The new release 12.5 solves this bug. https://github.com/jlolling/talendcomp_tFileExcel/releases
