### ISSUE TITLE
tFileExcelSheetInput: Formula is read instead of the value

### ISSUE THREAD

**Issue by EdoFede** [jlolling/talendcomp_tFileExcel#28]
Hi,
first of all, thank you for developing these great plugins for Talend.

I ran into a rather strange problem using the "tFileExcelSheetInput" component.

In some cases, apparently without a logical explanation, the plugin fails to interpret some formulas on the excel sheet that is being imported.
As a result, in the corresponding field of the imported data, I find the formula in textual format (but without the "=" character at the beginning) instead of the calculated value.
The strange thing is that the adjacent cell of the same sheet, has a practically identical formula, which is interpreted correctly instead.

If I process the same sheet with the "FileInputExcel" standard component on Talend, all the formulas are evaluated correctly.

I have been using your components with absolute success for several months, always with the same source excel sheet and in different jobs. Suddenly, with no obvious correlation, I started having these problems, only in a few cases (but growing).

I've tried anything to isolate and catch the problem (also manually rebuild of the sheet from the original untouched template, pasting only the values), but without success.

I tried a few days ago to update the components to the latest version (12.5), but the behavior remained unchanged.
Now I've built a new test job in talend from scratch and here too the problem is present.

I attach some examples.

Formula of the column correctly interpreted:
<img width="581" alt="SourceXLS_Formula1" src="https://user-images.githubusercontent.com/18591616/114880840-b93f7900-9e02-11eb-9758-e1d136468c2a.png">

Formula of the column incorrectly interpreted:
<img width="591" alt="SourceXLS_Formula2" src="https://user-images.githubusercontent.com/18591616/114880861-bd6b9680-9e02-11eb-8f39-a535689a5b5a.png">

Test job on talend - sequential extraction from the same file/sheet using the two components:
<img width="582" alt="TestJob" src="https://user-images.githubusercontent.com/18591616/114881069-f277e900-9e02-11eb-9c2f-8ca71c1ee2d0.png">

Log result:
<img width="1060" alt="LogResult" src="https://user-images.githubusercontent.com/18591616/114881121-002d6e80-9e03-11eb-8674-f277bb50026d.png">

I don't know if I'm the only one who has had these strange problems, but I hope my case can help pinpoint and fix the problem. :-)

**Comment by jlolling** [comment]
Hi, sorry for the delay of my answer. Yes you are right. This is strange.
Could you send me an example file to read. I cannot reproduce it with selfmade examples.
Please send the file to: jan.lolling@gmail.com

**Comment by EdoFede** [comment]
Sorry for my very late answer, I had a little accident and forgot to reply.

I've prepared a test file (deleting customer's sensitive infos) and tested obtaining the same result ad my original message.
I'll send you in some minutes at your Email address.

**Comment by jlolling** [comment]
The issue is solved with the latest version of the components. The problem appears if the formula is broken or cannot be evaluated and the actual data type of the cell was numeric.
