### ISSUE TITLE
tFileExcelWorkBookSave  not updating Pivot table

### ISSUE THREAD

**Issue by dorel14** [jlolling/talendcomp_tFileExcel#29]
Hello 
I have a job with 
TFileExcelWorkBookOpen  that open a template workbook

In the workbook 2 sheets 
- 1 with a table
- 1 with a pivot table made with data from table on first sheet
- 
tFileExcelSheetOutput  => to update data in table => This works perfect 

TFileExcelWorkBookSave => this save the workbook but pivot table is not refreshed 
![image](https://user-images.githubusercontent.com/10910133/119810954-d7f75c00-bee6-11eb-9cfd-1b363d8f6309.png)

My talend version is 7.3.1
tFileExcel version 12.5

**Comment by jlolling** [comment]
Could you please post here a screenshot from your job design?
Please take care you trigger the tFileExcelWorkBookSave with an OnSubjobOk because otherwise it is possible the actual post processing of the component tFileExcelSheetOutput is not done. I had mad such mistake and it took many hours for me until I realised the problem.

**Comment by dorel14** [comment]
Here it is
![image](https://user-images.githubusercontent.com/10910133/119819622-dcc10d80-bef0-11eb-903e-9243a083e3fc.png)

**Comment by dorel14** [comment]
hello some news

**Comment by jlolling** [comment]
The formula evaluation is not the function which refreshs the pivot table. Please take care the pivot-table is configured as "update when document is opened". 
![Screenshot 2021-08-23 at 19 24 45](https://user-images.githubusercontent.com/8038781/130490479-30708ddc-0a4a-4b95-9edb-825e4dbee783.png)

**Comment by jlolling** [comment]
In my tests is works this way.

**Comment by jlolling** [comment]
Does me explanation solved your issue. If not we can have a zoom session to figure out what went wrong.
Please contact me directly jan.lolling@gmail.com
