### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dorel14** [jlolling/talendcomp_tFileExcel#30]
Hello 
I would be nice if we can save an excel file / sheet  as pdf , it's possible with excel > 2007 and for the moment i have to execute a vbs to make the job .

Thx

**Comment by jlolling** [comment]
This is not possible. If you want to create PDF files I suggest you use JasperReports. There is also a component reading JasperReport designs and fill this report based on a csv file of database connection and you can have the report result (which can looks very appealing) as PDF file.
https://github.com/jlolling/talendcomp_tJasperReportExec
Look here to the documentation: https://github.com/jlolling/talendcomp_tJasperReportExec/blob/master/doc/tJasperReportExec.pdf
