### ISSUE TITLE
Exporting Sql DB Data to Mutliple Excel Sheet

### ISSUE THREAD

**Issue by shankarreshmimath** [jlolling/talendcomp_tFileExcel#32]
Hi,

I am unable to export data from SQL DB data to Excel as data exceeding 1048560 lines, need your help in exporting the data to multiple sheets in Excel.

**Comment by jlolling** [comment]
This a question of job design and has nothing to do with the components itself.
You have to find a way to partition the data into datasets with less 1M records. 
Best way is to find a criteria e.g. data range or a organisation or any type to split the data.
If you have found out how to split the data than setup multiple subjobs and transport the data into their own sheet.
