### ISSUE TITLE
The type org.apache.poi.ss.usermodel.Workbook cannot be resolved. It is indirectly referenced from required .class files

### ISSUE THREAD

**Issue by robstermn** [jlolling/talendcomp_tFileExcel#35]
I had to re-install Studio and when I added the "tFileExcel-Components" and ran my job I get the following error?
Hoping for a little help.

The type org.apache.poi.ss.usermodel.Workbook cannot be resolved. It is indirectly referenced from required .class files

**Comment by jlolling** [comment]
Can you please check if the problem persist if you use the preferences->Talend->Components->Change the Custom Component Path by adding or remove the last slash or backslash and klick on Apply.
What edition + version of the studio do you have?

**Comment by robstermn** [comment]
I'm running 
Version: 8.0.1
Build id: R2022-11

And I installed the compoents from the Suport/Exchange option.

And when I added them to a job it said that it was missing drivers and I had to manully add the drivers.

So I wonder if thats the problem?  is there a way to re-define the drivers needed for the compents?

Thanks again for the help.

**Comment by robstermn** [comment]
Thanks for update,
I would really like to use your compents over the defaults that come with Talend for Excel. but at this point until I can figure out a way to re-install the correct drivers , I'm stuck with using the defaults...

**Comment by jlolling** [comment]
I will keep you updated. If the build-in are good enough for the task, I would always recommend using them.

**Comment by robstermn** [comment]
The build-in's are okay and just woking, I really like the flexabilty and the added features of your compents and got used to using them.  

Hopefully there is a way to easily re-install the drivers for them?
