### ISSUE TITLE
Declaration of POI Version

### ISSUE THREAD

**Issue by mattywausb** [jlolling/talendcomp_tFileExcel#8]
Please declare the included poi version in the version string on the "advanced" page of the componenten properties. Probably also document, which version of talend components can be used in the same job, without getting poi library conflicts.

**Comment by jlolling** [comment]
I have notified the Apache-POI version in the release notes of the current release.

**Comment by mattywausb** [comment]
Where do I find the releasenotes ?

**Comment by jlolling** [comment]
I will mention the used Apache POI version in the release section.
